# Site settings
title: Namitor
email: wangzi6147@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Try Everything, you name it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://namitor.github.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Namitor

# Build settings
markdown: kramdown
